### PR TITLE
#19 - adds installation instructions for Ubuntu users

### LINKED ISSUE #19: No setup info on Ubuntu :'(
Currently there's no info for Ubuntu-users, on how to setup/install Postgres...
It would be great if there was some description on:

- how to install Postgres on our machines
- how to access the client

### PR DESCRIPTION
**Pull request by mk4111**
Closes #19

Summary of instructions for ubuntu-users to install and get started on postgres!

### CODE REVIEW

**Comment by mk4111** [comment]
Hi @nelsonic - could you please have a quick look at this PR and let me know if it's ok please? Thank you!

**Comment by nelsonic** [comment]
@mk4111 this looks great. you've _reminded_ me that we need to _clarify_ our "conventions" around specifying terminal commands in markdown ... https://github.com/dwyl/contributing/issues/35 😉

**Comment by mk4111** [comment]
Hi @nelsonic! Just updated the README.md to fit the formatting of the rest of the file! Hope this is what was being requested for!

**Comment by nelsonic** [comment]
@mk4111 _sweet_ thanks! 🎉

**Pull request merged**
